/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainForm;

import Compnay.myCompany;
import java.io.IOException; // dont remove for INI file
import article.Article;
import client.Client;
import consultation.Availability;
import consultation.Clients;
import consultation.ClientsMoney;
import consultation.ConsultationArticles;
import consultation.ConsultationDelivery;
import consultation.ConsultationSales;
import consultation.ConsultationTurnover;
import consultation.ForDelivery;
import consultation.SaleCosts;
import consultation.wrhAvailability;
import delivery.Delivery;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import priceLists.PriceLists;
import sale.SALE;
import settings.Countries;
import login.Login;
import static Tools.getConnection.getConnection;
import consultation.ConsultationCreditNotes;
import consultation.ConsultationOffers;
import consultation.SQLconsole;
import java.awt.Color;
import javax.swing.JSpinner;
import settings.Channels;
import settings.DealTypes;
import settings.Generator;
import settings.Measures;
import settings.PaymentTypes;
import rest.RestService;
import Tools.ArchiveDataBase;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import jsonImport.jsonImport;
import org.json.simple.parser.ParseException;
import xmlImport.xmlImport;
/**
 *
 * @author Viko
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public MainForm() {
        initComponents();
        setDate();
        jUser.setText("Потребител: " + Login.user);
        jmiReversal.setVisible(false);
    }

    private void setDate() {
        String Date = new SimpleDateFormat("dd.MM.yyyy").format(Calendar.getInstance().getTime());
        jDate.setText("Дата: " + Date);

        File directory = new File(".");
        String absolutePath = directory.getAbsolutePath().substring(0, directory.getAbsolutePath().length() - 1);

        jPicture.setIcon(new ImageIcon(new javax.swing.ImageIcon(absolutePath
                + "Pictures\\Picture.jpeg").getImage().getScaledInstance(jPicture.getWidth(),
                jPicture.getHeight(), Image.SCALE_SMOOTH)));

    }

    public ImageIcon ResizeImage(String ImagePath, byte[] pic) {
        ImageIcon myImage = null;
        if (ImagePath != null) {
            myImage = new ImageIcon(ImagePath);
        } else {
            myImage = new ImageIcon(pic);
        }

        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(myCompany.jChoosedPicture.getWidth(), myCompany.jChoosedPicture.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jbtnFastFirm = new javax.swing.JButton();
        jtbnFastPriceLists = new javax.swing.JButton();
        jbtnFastArticle = new javax.swing.JButton();
        jbtnFastClient = new javax.swing.JButton();
        jbtnFastDelivery = new javax.swing.JButton();
        jbtnFastSale = new javax.swing.JButton();
        jUser = new javax.swing.JLabel();
        jDate = new javax.swing.JLabel();
        jfbOffer = new javax.swing.JButton();
        jfbCreditNote = new javax.swing.JButton();
        jbtnArchiveDb = new javax.swing.JButton();
        jbtnImport = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPicture = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmOperaction = new javax.swing.JMenu();
        jmiSale = new javax.swing.JMenuItem();
        jmiDelivery = new javax.swing.JMenuItem();
        jbtnOffer = new javax.swing.JMenuItem();
        jbtnCredit = new javax.swing.JMenuItem();
        jmiFTPArchive = new javax.swing.JMenuItem();
        jmiImport = new javax.swing.JMenuItem();
        jmiImportXml = new javax.swing.JMenuItem();
        jmSales = new javax.swing.JMenu();
        jmiSaleDay = new javax.swing.JMenuItem();
        jmiSaleMonth = new javax.swing.JMenuItem();
        jmiSaleYear = new javax.swing.JMenuItem();
        jmiSaleArticles = new javax.swing.JMenuItem();
        jmiCreditReports = new javax.swing.JMenuItem();
        jmiOfferReports = new javax.swing.JMenuItem();
        jmDelivery = new javax.swing.JMenu();
        jmiDeliveryMonth = new javax.swing.JMenuItem();
        jmiDeliveryYear = new javax.swing.JMenuItem();
        jmiDeliveryArticles = new javax.swing.JMenuItem();
        jmReports = new javax.swing.JMenu();
        jmiTurnover = new javax.swing.JMenuItem();
        jmiExpenses = new javax.swing.JMenuItem();
        jmiAvailability = new javax.swing.JMenuItem();
        jmiWrhAvailability = new javax.swing.JMenuItem();
        jmiForDelivery = new javax.swing.JMenuItem();
        jmiMoney = new javax.swing.JMenuItem();
        jmiReversal = new javax.swing.JMenuItem();
        jmiClientsReport = new javax.swing.JMenuItem();
        jmCustomConsultation = new javax.swing.JMenuItem();
        jmSettings = new javax.swing.JMenu();
        jmiArticles = new javax.swing.JMenuItem();
        jmiClients = new javax.swing.JMenuItem();
        jmiFirms = new javax.swing.JMenuItem();
        jmiPriceList = new javax.swing.JMenuItem();
        jmiMeasure = new javax.swing.JMenuItem();
        jmiChannels = new javax.swing.JMenuItem();
        jmiDealType = new javax.swing.JMenuItem();
        JmiPayments = new javax.swing.JMenuItem();
        jmiCountries = new javax.swing.JMenuItem();
        jmiGenerator = new javax.swing.JMenuItem();
        jmiRest = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Главно Меню");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                onExit(evt);
            }
        });

        jbtnFastFirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/firm32.png"))); // NOI18N
        jbtnFastFirm.setToolTipText("Моята фирма!");
        jbtnFastFirm.setFocusPainted(false);
        jbtnFastFirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFastFirmActionPerformed(evt);
            }
        });

        jtbnFastPriceLists.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/priceList32.png"))); // NOI18N
        jtbnFastPriceLists.setToolTipText("Ценови листи!");
        jtbnFastPriceLists.setFocusPainted(false);
        jtbnFastPriceLists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnFastPriceListsActionPerformed(evt);
            }
        });

        jbtnFastArticle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/article32.png"))); // NOI18N
        jbtnFastArticle.setToolTipText("Нов артикул!");
        jbtnFastArticle.setFocusPainted(false);
        jbtnFastArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFastArticleActionPerformed(evt);
            }
        });

        jbtnFastClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/Client32.png"))); // NOI18N
        jbtnFastClient.setToolTipText("Нов Клиент!");
        jbtnFastClient.setFocusPainted(false);
        jbtnFastClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFastClientActionPerformed(evt);
            }
        });

        jbtnFastDelivery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/delivery32.png"))); // NOI18N
        jbtnFastDelivery.setToolTipText("Доставка!");
        jbtnFastDelivery.setFocusPainted(false);
        jbtnFastDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFastDeliveryActionPerformed(evt);
            }
        });

        jbtnFastSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/sale32.png"))); // NOI18N
        jbtnFastSale.setToolTipText("Продажба!");
        jbtnFastSale.setFocusPainted(false);
        jbtnFastSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFastSaleActionPerformed(evt);
            }
        });

        jUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jUser.setText("Потребител");
        jUser.setToolTipText("");

        jDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jDate.setText("Дата");
        jDate.setToolTipText("");

        jfbOffer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/offer 32x32.png"))); // NOI18N
        jfbOffer.setToolTipText("Оферта!");
        jfbOffer.setFocusPainted(false);
        jfbOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfbOfferActionPerformed(evt);
            }
        });

        jfbCreditNote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/creditNote 32x32.png"))); // NOI18N
        jfbCreditNote.setToolTipText("Кредитно известие!");
        jfbCreditNote.setFocusPainted(false);
        jfbCreditNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfbCreditNoteActionPerformed(evt);
            }
        });

        jbtnArchiveDb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/Archive32.png"))); // NOI18N
        jbtnArchiveDb.setToolTipText("Архивиране на базата данни!");
        jbtnArchiveDb.setFocusPainted(false);
        jbtnArchiveDb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnArchiveDbActionPerformed(evt);
            }
        });

        jbtnImport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/Import32.png"))); // NOI18N
        jbtnImport.setToolTipText("Импортиране на данни от уеб магазин! (json)");
        jbtnImport.setFocusPainted(false);
        jbtnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnImportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jbtnFastSale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnFastDelivery)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jfbOffer, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jfbCreditNote, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnFastClient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnFastArticle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtbnFastPriceLists)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnFastFirm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnArchiveDb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnImport, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jfbOffer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jfbCreditNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnFastSale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnFastDelivery, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnFastClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnFastArticle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtbnFastPriceLists, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnFastFirm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnArchiveDb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnImport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        jPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPicture.setToolTipText("");
        jPicture.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPicture.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPicture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPicture, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
        );

        jmOperaction.setText("ОПЕРАЦИИ");

        jmiSale.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jmiSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/sale32.png"))); // NOI18N
        jmiSale.setText("Продажба");
        jmiSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSaleActionPerformed(evt);
            }
        });
        jmOperaction.add(jmiSale);

        jmiDelivery.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jmiDelivery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/delivery32.png"))); // NOI18N
        jmiDelivery.setText("Доставка");
        jmiDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDeliveryActionPerformed(evt);
            }
        });
        jmOperaction.add(jmiDelivery);

        jbtnOffer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jbtnOffer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/offer 32x32.png"))); // NOI18N
        jbtnOffer.setText("Оферта");
        jbtnOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOfferActionPerformed(evt);
            }
        });
        jmOperaction.add(jbtnOffer);

        jbtnCredit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/creditNote 32x32.png"))); // NOI18N
        jbtnCredit.setText("Кредитно известие");
        jbtnCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCreditActionPerformed(evt);
            }
        });
        jmOperaction.add(jbtnCredit);

        jmiFTPArchive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/Archive32.png"))); // NOI18N
        jmiFTPArchive.setText("FTP Архив");
        jmiFTPArchive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFTPArchiveActionPerformed(evt);
            }
        });
        jmOperaction.add(jmiFTPArchive);

        jmiImport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/Import32.png"))); // NOI18N
        jmiImport.setText("Импорт (json)");
        jmiImport.setToolTipText("");
        jmiImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiImportActionPerformed(evt);
            }
        });
        jmOperaction.add(jmiImport);

        jmiImportXml.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/Import32.png"))); // NOI18N
        jmiImportXml.setText("Импорт (xml)");
        jmiImportXml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiImportXmlActionPerformed(evt);
            }
        });
        jmOperaction.add(jmiImportXml);

        jMenuBar1.add(jmOperaction);

        jmSales.setText("ПРОДАЖБИ");

        jmiSaleDay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/report32.png"))); // NOI18N
        jmiSaleDay.setText("За деня");
        jmiSaleDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSaleDayActionPerformed(evt);
            }
        });
        jmSales.add(jmiSaleDay);

        jmiSaleMonth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/report32.png"))); // NOI18N
        jmiSaleMonth.setText("За месеца");
        jmiSaleMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSaleMonthActionPerformed(evt);
            }
        });
        jmSales.add(jmiSaleMonth);

        jmiSaleYear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/report32.png"))); // NOI18N
        jmiSaleYear.setText("За годината");
        jmiSaleYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSaleYearActionPerformed(evt);
            }
        });
        jmSales.add(jmiSaleYear);

        jmiSaleArticles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/report32.png"))); // NOI18N
        jmiSaleArticles.setText("По артикули");
        jmiSaleArticles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSaleArticlesActionPerformed(evt);
            }
        });
        jmSales.add(jmiSaleArticles);

        jmiCreditReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/report32.png"))); // NOI18N
        jmiCreditReports.setText("Сторнирани продажби");
        jmiCreditReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCreditReportsActionPerformed(evt);
            }
        });
        jmSales.add(jmiCreditReports);

        jmiOfferReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/report32.png"))); // NOI18N
        jmiOfferReports.setText("Оферти");
        jmiOfferReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOfferReportsActionPerformed(evt);
            }
        });
        jmSales.add(jmiOfferReports);

        jMenuBar1.add(jmSales);

        jmDelivery.setText("ДОСТАВКИ");

        jmiDeliveryMonth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/report32.png"))); // NOI18N
        jmiDeliveryMonth.setText("За месеца");
        jmiDeliveryMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDeliveryMonthActionPerformed(evt);
            }
        });
        jmDelivery.add(jmiDeliveryMonth);

        jmiDeliveryYear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/report32.png"))); // NOI18N
        jmiDeliveryYear.setText("За годината");
        jmiDeliveryYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDeliveryYearActionPerformed(evt);
            }
        });
        jmDelivery.add(jmiDeliveryYear);

        jmiDeliveryArticles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/report32.png"))); // NOI18N
        jmiDeliveryArticles.setText("По артикули");
        jmiDeliveryArticles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDeliveryArticlesActionPerformed(evt);
            }
        });
        jmDelivery.add(jmiDeliveryArticles);

        jMenuBar1.add(jmDelivery);

        jmReports.setText("СПРАВКИ");

        jmiTurnover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/report32.png"))); // NOI18N
        jmiTurnover.setText("Приходи");
        jmiTurnover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTurnoverActionPerformed(evt);
            }
        });
        jmReports.add(jmiTurnover);

        jmiExpenses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/report32.png"))); // NOI18N
        jmiExpenses.setText("Разходи");
        jmiExpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExpensesActionPerformed(evt);
            }
        });
        jmReports.add(jmiExpenses);

        jmiAvailability.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/report32.png"))); // NOI18N
        jmiAvailability.setText("Склад");
        jmiAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAvailabilityActionPerformed(evt);
            }
        });
        jmReports.add(jmiAvailability);

        jmiWrhAvailability.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/report32.png"))); // NOI18N
        jmiWrhAvailability.setText("Счет. наличност");
        jmiWrhAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiWrhAvailabilityActionPerformed(evt);
            }
        });
        jmReports.add(jmiWrhAvailability);

        jmiForDelivery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/report32.png"))); // NOI18N
        jmiForDelivery.setText("За доставка");
        jmiForDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiForDeliveryActionPerformed(evt);
            }
        });
        jmReports.add(jmiForDelivery);

        jmiMoney.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/report32.png"))); // NOI18N
        jmiMoney.setText("Оборот");
        jmiMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMoneyActionPerformed(evt);
            }
        });
        jmReports.add(jmiMoney);

        jmiReversal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/report32.png"))); // NOI18N
        jmiReversal.setText("Сторнирани (Не се поддържа)!!!");
        jmiReversal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiReversalActionPerformed(evt);
            }
        });
        jmReports.add(jmiReversal);

        jmiClientsReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/report32.png"))); // NOI18N
        jmiClientsReport.setText("Клиенти");
        jmiClientsReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClientsReportActionPerformed(evt);
            }
        });
        jmReports.add(jmiClientsReport);

        jmCustomConsultation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/report32.png"))); // NOI18N
        jmCustomConsultation.setText("SQL конзола");
        jmCustomConsultation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCustomConsultationActionPerformed(evt);
            }
        });
        jmReports.add(jmCustomConsultation);

        jMenuBar1.add(jmReports);

        jmSettings.setText("НАСТРОЙКИ");

        jmiArticles.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jmiArticles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/article32.png"))); // NOI18N
        jmiArticles.setText("Артикули");
        jmiArticles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiArticlesActionPerformed(evt);
            }
        });
        jmSettings.add(jmiArticles);

        jmiClients.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jmiClients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/Client32.png"))); // NOI18N
        jmiClients.setText("Клиенти");
        jmiClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClientsActionPerformed(evt);
            }
        });
        jmSettings.add(jmiClients);

        jmiFirms.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jmiFirms.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/firm32.png"))); // NOI18N
        jmiFirms.setText("Фирмени данни");
        jmiFirms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFirmsActionPerformed(evt);
            }
        });
        jmSettings.add(jmiFirms);

        jmiPriceList.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jmiPriceList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/priceList32.png"))); // NOI18N
        jmiPriceList.setText("Ценови листи");
        jmiPriceList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPriceListActionPerformed(evt);
            }
        });
        jmSettings.add(jmiPriceList);

        jmiMeasure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/measure32.png"))); // NOI18N
        jmiMeasure.setText("Мерни единици");
        jmiMeasure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMeasureActionPerformed(evt);
            }
        });
        jmSettings.add(jmiMeasure);

        jmiChannels.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/channels32.png"))); // NOI18N
        jmiChannels.setText("Канали");
        jmiChannels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiChannelsActionPerformed(evt);
            }
        });
        jmSettings.add(jmiChannels);

        jmiDealType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/deals32.png"))); // NOI18N
        jmiDealType.setText("Типове сделки");
        jmiDealType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDealTypeActionPerformed(evt);
            }
        });
        jmSettings.add(jmiDealType);

        JmiPayments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/payments32.png"))); // NOI18N
        JmiPayments.setText("Начини на плащане");
        JmiPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiPaymentsActionPerformed(evt);
            }
        });
        jmSettings.add(JmiPayments);

        jmiCountries.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/Country.png"))); // NOI18N
        jmiCountries.setText("Държави");
        jmiCountries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCountriesActionPerformed(evt);
            }
        });
        jmSettings.add(jmiCountries);

        jmiGenerator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/Generator32.png"))); // NOI18N
        jmiGenerator.setText("Фактура номер");
        jmiGenerator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGeneratorActionPerformed(evt);
            }
        });
        jmSettings.add(jmiGenerator);

        jmiRest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainForm/Rest32.png"))); // NOI18N
        jmiRest.setText("REST");
        jmiRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRestActionPerformed(evt);
            }
        });
        jmSettings.add(jmiRest);

        jMenuBar1.add(jmSettings);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSaleActionPerformed
        SALE sale = new SALE();
        sale.setVisible(true);
    }//GEN-LAST:event_jmiSaleActionPerformed

    private void jmiDeliveryArticlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDeliveryArticlesActionPerformed
        ConsultationArticles articlesConsult = new ConsultationArticles();
        articlesConsult.Type = 2;
        articlesConsult.jButton1.doClick();
        articlesConsult.setVisible(true);
        articlesConsult.jTable1.getColumnModel().getColumn(3).setHeaderValue("Брой доставени");
    }//GEN-LAST:event_jmiDeliveryArticlesActionPerformed

    private void jmiClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClientsActionPerformed
        Client client = new Client();
        client.isFromForm = 0;
        client.setVisible(true);
    }//GEN-LAST:event_jmiClientsActionPerformed

    private void jmiDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDeliveryActionPerformed
        Delivery delivery = new Delivery();
        delivery.setVisible(true);
        delivery.jcbDealType.setSelectedIndex(3);
    }//GEN-LAST:event_jmiDeliveryActionPerformed

    private void jmiSaleDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSaleDayActionPerformed
        ConsultationSales sales = new ConsultationSales();
        sales.jButton1.doClick();
        sales.setVisible(true);
    }//GEN-LAST:event_jmiSaleDayActionPerformed

    private void jmiAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAvailabilityActionPerformed
        Availability ava = new Availability();
        ava.setVisible(true);
    }//GEN-LAST:event_jmiAvailabilityActionPerformed

    private void jmiMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMoneyActionPerformed
        ClientsMoney clients = new ClientsMoney();
        clients.setVisible(true);
    }//GEN-LAST:event_jmiMoneyActionPerformed

    private void jmiArticlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiArticlesActionPerformed
        Article article = new Article();
        article.setVisible(true);
    }//GEN-LAST:event_jmiArticlesActionPerformed

    private void jmiPriceListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPriceListActionPerformed
        PriceLists price = new PriceLists();
        price.setVisible(true);
    }//GEN-LAST:event_jmiPriceListActionPerformed

    private void jmiDealTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDealTypeActionPerformed
        DealTypes dealTypes = new DealTypes();
        dealTypes.setVisible(true);
    }//GEN-LAST:event_jmiDealTypeActionPerformed

    private void JmiPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiPaymentsActionPerformed
        PaymentTypes payment = new PaymentTypes();
        payment.setVisible(true);
    }//GEN-LAST:event_JmiPaymentsActionPerformed

    private void jmiChannelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiChannelsActionPerformed
        Channels channels = new Channels();
        channels.setVisible(true);
    }//GEN-LAST:event_jmiChannelsActionPerformed

    private void jmiMeasureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMeasureActionPerformed
        Measures measures = new Measures();
        measures.setVisible(true);
    }//GEN-LAST:event_jmiMeasureActionPerformed

    private void jmiFirmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFirmsActionPerformed
        myCompany company = new myCompany();
        try {
            Connection con = getConnection();
            PreparedStatement ps = con.prepareStatement("select MC.NAME, MC.COUNTRY, MC.CITY, MC.ADDRESS, MC.MOL, MC.LOGO, "
                    + "MC.VAT_PERCENTAGE,\n"
                    + "MC.PHONES, MC.SITE, MC.MAIL, MC.BANK, MC.CONTO_NU, MC.IBAN, MC.BIC,\n"
                    + "MC.VAT_NUMBER, MC.GREICHT, MC.HRB\n"
                    + "from MY_COMPANY MC where MC.ID = 1");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                myCompany.jtxtName.setText(rs.getString("NAME"));
                myCompany.jtxtState.setText(rs.getString("COUNTRY"));
                myCompany.jtxtCity.setText(rs.getString("CITY"));
                myCompany.jtxtAddress.setText(rs.getString("ADDRESS"));
                myCompany.jtxtMol.setText(rs.getString("MOL"));
                myCompany.jtxtVatPercent.setText(rs.getString("VAT_PERCENTAGE"));
                myCompany.jtxtPhone.setText(rs.getString("PHONES"));
                myCompany.jtxtSite.setText(rs.getString("SITE"));
                myCompany.jtxtEmail.setText(rs.getString("MAIL"));
                myCompany.jtxtBank.setText(rs.getString("BANK"));
                myCompany.jtxtConto.setText(rs.getString("CONTO_NU"));
                myCompany.jtxtIBAN.setText(rs.getString("IBAN"));
                myCompany.jtxtBIC.setText(rs.getString("BIC"));
                myCompany.jtxtVatNumber.setText(rs.getString("VAT_NUMBER"));
                myCompany.jtxtGreicht.setText(rs.getString("GREICHT"));
                myCompany.jtxtHRB.setText(rs.getString("HRB"));
                myCompany.jChoosedPicture.setIcon(ResizeImage(null, rs.getBytes("LOGO")));
            }
            company.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jmiFirmsActionPerformed

    private void jbtnFastSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFastSaleActionPerformed
        SALE sale = new SALE();
        sale.setVisible(true);
    }//GEN-LAST:event_jbtnFastSaleActionPerformed

    private void jbtnFastDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFastDeliveryActionPerformed
        Delivery delivery = new Delivery();
        delivery.setVisible(true);
        delivery.jcbDealType.setSelectedIndex(3);
    }//GEN-LAST:event_jbtnFastDeliveryActionPerformed

    private void jbtnFastClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFastClientActionPerformed
        Client client = new Client();
        client.setVisible(true);
        client.isFromForm = 0;
    }//GEN-LAST:event_jbtnFastClientActionPerformed

    private void jbtnFastArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFastArticleActionPerformed
        Article article = new Article();
        article.setVisible(true);
    }//GEN-LAST:event_jbtnFastArticleActionPerformed

    private void jtbnFastPriceListsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnFastPriceListsActionPerformed
        PriceLists price = new PriceLists();
        price.setVisible(true);
    }//GEN-LAST:event_jtbnFastPriceListsActionPerformed

    private void jbtnFastFirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFastFirmActionPerformed
        myCompany company = new myCompany();
        company.setVisible(true);
        try {
            Connection con = getConnection();
            PreparedStatement ps = con.prepareStatement("select MC.NAME, MC.COUNTRY, MC.CITY, MC.ADDRESS, MC.MOL, MC.LOGO, "
                    + "MC.VAT_PERCENTAGE,\n"
                    + "MC.PHONES, MC.SITE, MC.MAIL, MC.BANK, MC.CONTO_NU, MC.IBAN, MC.BIC,\n"
                    + "MC.VAT_NUMBER, MC.GREICHT, MC.HRB\n"
                    + "from MY_COMPANY MC where MC.ID = 1");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                myCompany.jtxtName.setText(rs.getString("NAME"));
                myCompany.jtxtState.setText(rs.getString("COUNTRY"));
                myCompany.jtxtCity.setText(rs.getString("CITY"));
                myCompany.jtxtAddress.setText(rs.getString("ADDRESS"));
                myCompany.jtxtMol.setText(rs.getString("MOL"));
                myCompany.jtxtVatPercent.setText(rs.getString("VAT_PERCENTAGE"));
                myCompany.jtxtPhone.setText(rs.getString("PHONES"));
                myCompany.jtxtSite.setText(rs.getString("SITE"));
                myCompany.jtxtEmail.setText(rs.getString("MAIL"));
                myCompany.jtxtBank.setText(rs.getString("BANK"));
                myCompany.jtxtConto.setText(rs.getString("CONTO_NU"));
                myCompany.jtxtIBAN.setText(rs.getString("IBAN"));
                myCompany.jtxtBIC.setText(rs.getString("BIC"));
                myCompany.jtxtVatNumber.setText(rs.getString("VAT_NUMBER"));
                myCompany.jtxtGreicht.setText(rs.getString("GREICHT"));
                myCompany.jtxtHRB.setText(rs.getString("HRB"));
                myCompany.jChoosedPicture.setIcon(ResizeImage(null, rs.getBytes("LOGO")));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jbtnFastFirmActionPerformed

    private void jmiSaleMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSaleMonthActionPerformed
        ConsultationSales sales = new ConsultationSales();
        Date date = new Date();
        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.DATE, cal.getActualMinimum(Calendar.DATE));
        Date firstDayOfMonth = cal.getTime();
        sales.jdToDate.setDate(date);
        sales.jdFromDate.setDate(firstDayOfMonth);
        sales.jButton1.doClick();
        sales.setVisible(true);
    }//GEN-LAST:event_jmiSaleMonthActionPerformed

    private void jmiSaleYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSaleYearActionPerformed
        ConsultationSales sales = new ConsultationSales();
        Calendar calfirst = Calendar.getInstance();
        calfirst.set(Calendar.DAY_OF_YEAR, calfirst.getActualMinimum(Calendar.DAY_OF_YEAR));
        Date firstDayOfYear = calfirst.getTime();
        Calendar calLast = Calendar.getInstance();
        calLast.set(Calendar.DAY_OF_YEAR, calfirst.getActualMaximum(Calendar.DAY_OF_YEAR));
        Date lastDatOfYear = calLast.getTime();
        sales.jdToDate.setDate(lastDatOfYear);
        sales.jdFromDate.setDate(firstDayOfYear);
        sales.jButton1.doClick();
        sales.setVisible(true);
    }//GEN-LAST:event_jmiSaleYearActionPerformed

    private void jmiDeliveryMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDeliveryMonthActionPerformed
        ConsultationDelivery reportDelivery = new ConsultationDelivery();
        Date date = new Date();
        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.DATE, cal.getActualMinimum(Calendar.DATE));
        Date firstDayOfMonth = cal.getTime();
        reportDelivery.jdToDate.setDate(date);
        reportDelivery.jdFromDate.setDate(firstDayOfMonth);
        reportDelivery.jButton1.doClick();
        reportDelivery.setVisible(true);
    }//GEN-LAST:event_jmiDeliveryMonthActionPerformed

    private void jmiDeliveryYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDeliveryYearActionPerformed
        ConsultationDelivery reportDelivery = new ConsultationDelivery();
        Calendar calfirst = Calendar.getInstance();
        calfirst.set(Calendar.DAY_OF_YEAR, calfirst.getActualMinimum(Calendar.DAY_OF_YEAR));
        Date firstDayOfYear = calfirst.getTime();
        Calendar calLast = Calendar.getInstance();
        calLast.set(Calendar.DAY_OF_YEAR, calfirst.getActualMaximum(Calendar.DAY_OF_YEAR));
        Date lastDatOfYear = calLast.getTime();
        reportDelivery.jdToDate.setDate(lastDatOfYear);
        reportDelivery.jdFromDate.setDate(firstDayOfYear);
        reportDelivery.jButton1.doClick();
        reportDelivery.setVisible(true);
    }//GEN-LAST:event_jmiDeliveryYearActionPerformed

    private void jmiReversalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiReversalActionPerformed
/*        ConsultationSales sales = new ConsultationSales();
        Date date = new Date();
        sales.Type = 3;
        sales.jlbConsultation.setText("Сторнирани");
        Calendar calfirst = Calendar.getInstance();
        calfirst.set(Calendar.DAY_OF_YEAR, calfirst.getActualMinimum(Calendar.DAY_OF_YEAR));
        Date firstDayOfYear = calfirst.getTime();
        sales.jdToDate.setDate(date);
        sales.jdFromDate.setDate(firstDayOfYear);
        sales.jButton1.doClick();
        sales.setVisible(true);*/
        JOptionPane.showMessageDialog(this, "Тази функционалност вече не се поддържа!!!");
    }//GEN-LAST:event_jmiReversalActionPerformed

    private void jmiCountriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCountriesActionPerformed
        Countries country = new Countries();
        country.setVisible(true);
    }//GEN-LAST:event_jmiCountriesActionPerformed

    private void jmiSaleArticlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSaleArticlesActionPerformed
        ConsultationArticles articlesConsult = new ConsultationArticles();
        articlesConsult.Type = 1;
        articlesConsult.jButton1.doClick();
        articlesConsult.setVisible(true);
        articlesConsult.jTable1.getColumnModel().getColumn(3).setHeaderValue("Брой продадени");
    }//GEN-LAST:event_jmiSaleArticlesActionPerformed

    private void jmiTurnoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTurnoverActionPerformed
        ConsultationTurnover turnover = new ConsultationTurnover();
        Date date = new Date();
        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.DATE, cal.getActualMinimum(Calendar.DATE));
        Date firstDayOfMonth = cal.getTime();
        turnover.jdToDate.setDate(date);
        turnover.jdFromDate.setDate(firstDayOfMonth);
        turnover.jButton1.doClick();
        turnover.setVisible(true);
    }//GEN-LAST:event_jmiTurnoverActionPerformed

    private void jmiWrhAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiWrhAvailabilityActionPerformed
        wrhAvailability wrh = new wrhAvailability();
        Date date = new Date();
        wrh.jdFromDate.setDate(date);
        wrh.jButton1.doClick();
        wrh.setVisible(true);
    }//GEN-LAST:event_jmiWrhAvailabilityActionPerformed

    private void jmiForDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiForDeliveryActionPerformed
        ForDelivery forDelivery = new ForDelivery();
        forDelivery.setVisible(true);
    }//GEN-LAST:event_jmiForDeliveryActionPerformed

    private void jmiClientsReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClientsReportActionPerformed
        Clients clientReport = new Clients();
        clientReport.setVisible(true);
    }//GEN-LAST:event_jmiClientsReportActionPerformed

    private void jmiExpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExpensesActionPerformed
        SaleCosts saleCosts = new SaleCosts();
        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.DATE, cal.getActualMinimum(Calendar.DATE));
        Date firstDayOfMonth = cal.getTime();
        Date date = new Date();
        saleCosts.jdFromDate.setDate(firstDayOfMonth);
        saleCosts.jdToDate.setDate(date);
        saleCosts.jButton1.doClick();
        saleCosts.setVisible(true);
    }//GEN-LAST:event_jmiExpensesActionPerformed

    private void jmiGeneratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGeneratorActionPerformed
        Generator gen = new Generator();
        gen.setVisible(true);
    }//GEN-LAST:event_jmiGeneratorActionPerformed

    private void onExit(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onExit
        int dialogButton = JOptionPane.showConfirmDialog(null, "Сигурни ли сте, че искате да излезнете!", "Главно меню", JOptionPane.YES_NO_OPTION);
        if (dialogButton == JOptionPane.YES_OPTION) {
            System.exit(0);
            if (dialogButton == JOptionPane.NO_OPTION) {
                remove(dialogButton);
            }
        }
    }//GEN-LAST:event_onExit

    private void jmCustomConsultationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCustomConsultationActionPerformed
       SQLconsole console = new SQLconsole();
       console.setVisible(true);
    }//GEN-LAST:event_jmCustomConsultationActionPerformed

    private void jfbOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfbOfferActionPerformed
        SALE sale = new SALE();
        sale.jlbSale.setText("Оферта");
        sale.setTitle("Оферта");
        sale.jbntInvoice.setEnabled(false);
        sale.isOffer = 1;
        //sale.isSave = 1; // only for test check this!!!!
        sale.jtxtInvoiceNumber.setText("null/");
        sale.setVisible(true);
    }//GEN-LAST:event_jfbOfferActionPerformed

    private void jfbCreditNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfbCreditNoteActionPerformed
        SALE sale = new SALE();
        sale.jlbSale.setText("Сторнирана Продажба");
        sale.setTitle("Сторнирана Продажба");
        sale.jlbInvoiceNumbers.setText("Номер и дата на КИ:");
        sale.isCreditNote = 1;
        JSpinner.NumberEditor editor = new JSpinner.NumberEditor(sale.jtxtQty, "-#");
        sale.jtxtQty.setEditor(editor);
        sale.jxtCredit.setVisible(true);
        sale.jdtchCredit.setVisible(true);
        sale.jlbCredit.setVisible(true);
        sale.jlbCreditDate.setVisible(true);
        //sale.jbntInvoice.setEnabled(false);
        sale.jxtCredit.setBackground(Color.CYAN);
        sale.jbntInvoice.setText("КИ");
        sale.setVisible(true);
    }//GEN-LAST:event_jfbCreditNoteActionPerformed

    private void jbtnOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOfferActionPerformed
        SALE sale = new SALE();
        sale.jlbSale.setText("Оферта");
        sale.setTitle("Оферта");
        sale.jbntInvoice.setEnabled(false);
        sale.isOffer = 1;
        //sale.isSave = 1; // only for test check this!!!!
        sale.jtxtInvoiceNumber.setText("null/");
        sale.setVisible(true);
    }//GEN-LAST:event_jbtnOfferActionPerformed

    private void jbtnCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCreditActionPerformed
        SALE sale = new SALE();
        sale.jlbSale.setText("Сторнирана Продажба");
        sale.setTitle("Сторнирана Продажба");
        sale.isCreditNote = 1;
        sale.jlbInvoiceNumbers.setText("Номер и дата на КИ:");
        JSpinner.NumberEditor editor = new JSpinner.NumberEditor(sale.jtxtQty, "-#");
        sale.jtxtQty.setEditor(editor);
        sale.jtxtQty.setEditor(editor);
        sale.jxtCredit.setVisible(true);
        sale.jdtchCredit.setVisible(true);
        sale.jlbCredit.setVisible(true);
        sale.jlbCreditDate.setVisible(true);
        //sale.jbntInvoice.setEnabled(false);
        sale.jxtCredit.setBackground(Color.CYAN);
        sale.jbntInvoice.setText("КИ");
        sale.setVisible(true);
    }//GEN-LAST:event_jbtnCreditActionPerformed

    private void jmiCreditReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCreditReportsActionPerformed
        ConsultationCreditNotes credit = new ConsultationCreditNotes();

        credit.Type = 6;

        Date date = new Date();

        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.DATE, cal.getActualMinimum(Calendar.DATE));

        Date firstDayOfMonth = cal.getTime();

        credit.jdToDate.setDate(date);
        credit.jdFromDate.setDate(firstDayOfMonth);
        credit.jButton1.doClick();
        credit.setVisible(true);

    }//GEN-LAST:event_jmiCreditReportsActionPerformed

    private void jmiOfferReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOfferReportsActionPerformed
        ConsultationOffers offers = new ConsultationOffers();

        offers.Type = 5;

        Date date = new Date();

        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.DATE, cal.getActualMinimum(Calendar.DATE));

        Date firstDayOfMonth = cal.getTime();

        offers.jdToDate.setDate(date);
        offers.jdFromDate.setDate(firstDayOfMonth);
        offers.jButton1.doClick();
        offers.setVisible(true);
    }//GEN-LAST:event_jmiOfferReportsActionPerformed

    private void jmiRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRestActionPerformed
       RestService rest = new RestService();
       rest.setVisible(true);
    }//GEN-LAST:event_jmiRestActionPerformed

    private void jbtnArchiveDbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnArchiveDbActionPerformed
        ArchiveDataBase archivedb = new ArchiveDataBase();
        try {
            archivedb.archiveDb();
            JOptionPane.showMessageDialog(this, "Архива е успешно създаден!", "Архивиране", JOptionPane.NO_OPTION);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Грешка при създаването на архива!", "Архивиране", JOptionPane.NO_OPTION);
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Грешка при създаването на архива!", "Архивиране", JOptionPane.NO_OPTION);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Сървъра е недостъпен!", "Архивиране", JOptionPane.NO_OPTION);
        }
    }//GEN-LAST:event_jbtnArchiveDbActionPerformed

    private void jbtnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnImportActionPerformed
        jsonImport json = new jsonImport();
        try {
            json.importJson();
            JOptionPane.showMessageDialog(this, "Успешно импортиране!", "Импортиране", JOptionPane.NO_OPTION);
        } catch (IOException | ParseException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Файлът не е намерен!","Импортиране", JOptionPane.NO_OPTION);
        } catch (java.text.ParseException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, " Възникна грешка при импортиране!","Импортиране", JOptionPane.NO_OPTION);
        }
    }//GEN-LAST:event_jbtnImportActionPerformed

    private void jmiFTPArchiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFTPArchiveActionPerformed
        ArchiveDataBase archivedb = new ArchiveDataBase();
        try {
            archivedb.archiveDb();
            JOptionPane.showMessageDialog(this, "Архива е успешно създаден!", "Архивиране", JOptionPane.NO_OPTION);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Грешка при създаването на архива!", "Архивиране", JOptionPane.NO_OPTION);
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Грешка при създаването на архива!", "Архивиране", JOptionPane.NO_OPTION);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Сървъра е недостъпен!", "Архивиране", JOptionPane.NO_OPTION);
        }
    }//GEN-LAST:event_jmiFTPArchiveActionPerformed

    private void jmiImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiImportActionPerformed
        jsonImport json = new jsonImport();
        try {
            json.importJson();
            JOptionPane.showMessageDialog(this, "Успешно импортиране!", "Импортиране", JOptionPane.NO_OPTION);
        } catch (IOException | ParseException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Файлът не е намерен!","Импортиране", JOptionPane.NO_OPTION);
        } catch (java.text.ParseException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, " Възникна грешка при импортиране!","Импортиране", JOptionPane.NO_OPTION);
        }
    }//GEN-LAST:event_jmiImportActionPerformed

    private void jmiImportXmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiImportXmlActionPerformed
        xmlImport xml = new xmlImport();
        xml.importXML();
        JOptionPane.showMessageDialog(this, "Успешно импортиране!", "Импортиране", JOptionPane.NO_OPTION);
    }//GEN-LAST:event_jmiImportXmlActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem JmiPayments;
    private javax.swing.JLabel jDate;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel jPicture;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jUser;
    public javax.swing.JButton jbtnArchiveDb;
    private javax.swing.JMenuItem jbtnCredit;
    private javax.swing.JButton jbtnFastArticle;
    private javax.swing.JButton jbtnFastClient;
    private javax.swing.JButton jbtnFastDelivery;
    public javax.swing.JButton jbtnFastFirm;
    private javax.swing.JButton jbtnFastSale;
    public javax.swing.JButton jbtnImport;
    private javax.swing.JMenuItem jbtnOffer;
    private javax.swing.JButton jfbCreditNote;
    private javax.swing.JButton jfbOffer;
    private javax.swing.JMenuItem jmCustomConsultation;
    private javax.swing.JMenu jmDelivery;
    private javax.swing.JMenu jmOperaction;
    public javax.swing.JMenu jmReports;
    private javax.swing.JMenu jmSales;
    private javax.swing.JMenu jmSettings;
    private javax.swing.JMenuItem jmiArticles;
    private javax.swing.JMenuItem jmiAvailability;
    public javax.swing.JMenuItem jmiChannels;
    private javax.swing.JMenuItem jmiClients;
    private javax.swing.JMenuItem jmiClientsReport;
    public javax.swing.JMenuItem jmiCountries;
    private javax.swing.JMenuItem jmiCreditReports;
    public javax.swing.JMenuItem jmiDealType;
    private javax.swing.JMenuItem jmiDelivery;
    private javax.swing.JMenuItem jmiDeliveryArticles;
    private javax.swing.JMenuItem jmiDeliveryMonth;
    private javax.swing.JMenuItem jmiDeliveryYear;
    private javax.swing.JMenuItem jmiExpenses;
    public javax.swing.JMenuItem jmiFTPArchive;
    public javax.swing.JMenuItem jmiFirms;
    private javax.swing.JMenuItem jmiForDelivery;
    public javax.swing.JMenuItem jmiGenerator;
    public javax.swing.JMenuItem jmiImport;
    public javax.swing.JMenuItem jmiImportXml;
    public javax.swing.JMenuItem jmiMeasure;
    private javax.swing.JMenuItem jmiMoney;
    private javax.swing.JMenuItem jmiOfferReports;
    public javax.swing.JMenuItem jmiPriceList;
    public javax.swing.JMenuItem jmiRest;
    private javax.swing.JMenuItem jmiReversal;
    private javax.swing.JMenuItem jmiSale;
    private javax.swing.JMenuItem jmiSaleArticles;
    private javax.swing.JMenuItem jmiSaleDay;
    private javax.swing.JMenuItem jmiSaleMonth;
    private javax.swing.JMenuItem jmiSaleYear;
    private javax.swing.JMenuItem jmiTurnover;
    private javax.swing.JMenuItem jmiWrhAvailability;
    public javax.swing.JButton jtbnFastPriceLists;
    // End of variables declaration//GEN-END:variables
}
