/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import static Tools.getConnection.getConnection;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mainForm.MainForm;
import java.io.File;
import java.io.IOException; // Dont remove for ini File
import javax.swing.ImageIcon;
import org.ini4j.Wini; // Dont remove for ini File

/**
 *
 * @author Viko
 */
public class Login extends javax.swing.JFrame {

    int userType = 1;
    public static String user = null;
    public static int userID = 0;

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    /**
     * Creates new form Login
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public Login() {
        initComponents();
        this.getRootPane().setDefaultButton(jbtnLogin);
        File directory = new File(".");
        String absolutePath = directory.getAbsolutePath().substring(0, directory.getAbsolutePath().length() - 1);
        jMainPicture.setIcon(new ImageIcon(new javax.swing.ImageIcon(absolutePath
                + "Pictures\\LoginPicture.jpeg").getImage().getScaledInstance(jMainPicture.getWidth(),
                jMainPicture.getHeight(), Image.SCALE_SMOOTH)));
    }

    public void checkStatus() {
        Connection connection;
        PreparedStatement ps;
        try {
            connection = getConnection();
            ps = connection.prepareStatement("execute procedure CHECK_STATUS_ON_EXIT");
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jlbUsername = new javax.swing.JLabel();
        jlbPass = new javax.swing.JLabel();
        jtxtUserName = new javax.swing.JTextField();
        jTxtPassword = new javax.swing.JPasswordField();
        jlbLoginForm = new javax.swing.JLabel();
        jbtnLogin = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();
        jMainPicture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Вход");
        setBackground(new java.awt.Color(255, 255, 153));
        setForeground(new java.awt.Color(255, 255, 153));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 625, 403));
        setMinimumSize(new java.awt.Dimension(625, 403));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMaximumSize(new java.awt.Dimension(625, 403));
        jPanel1.setMinimumSize(new java.awt.Dimension(625, 403));
        jPanel1.setName("Login"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(null);

        jlbUsername.setBackground(new java.awt.Color(204, 204, 204));
        jlbUsername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbUsername.setForeground(new java.awt.Color(255, 255, 255));
        jlbUsername.setText("Потребител:");
        jPanel3.add(jlbUsername);
        jlbUsername.setBounds(140, 170, 118, 22);

        jlbPass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbPass.setForeground(new java.awt.Color(255, 255, 255));
        jlbPass.setText("Парола:");
        jPanel3.add(jlbPass);
        jlbPass.setBounds(140, 210, 77, 22);

        jtxtUserName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtUserName.setToolTipText("");
        jPanel3.add(jtxtUserName);
        jtxtUserName.setBounds(310, 170, 169, 22);
        jPanel3.add(jTxtPassword);
        jTxtPassword.setBounds(310, 210, 169, 22);

        jlbLoginForm.setBackground(new java.awt.Color(255, 255, 255));
        jlbLoginForm.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jlbLoginForm.setForeground(new java.awt.Color(255, 255, 255));
        jlbLoginForm.setText("Вход");
        jPanel3.add(jlbLoginForm);
        jlbLoginForm.setBounds(240, 30, 134, 76);

        jbtnLogin.setBackground(new java.awt.Color(102, 255, 51));
        jbtnLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnLogin.setForeground(new java.awt.Color(255, 255, 255));
        jbtnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/login.png"))); // NOI18N
        jbtnLogin.setText("Потвърди");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnLogin);
        jbtnLogin.setBounds(100, 330, 190, 37);

        jbtnCancel.setBackground(new java.awt.Color(255, 51, 0));
        jbtnCancel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnCancel.setForeground(new java.awt.Color(255, 255, 255));
        jbtnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/delete.png"))); // NOI18N
        jbtnCancel.setText("Отказ");
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnCancel);
        jbtnCancel.setBounds(320, 330, 190, 37);
        jPanel3.add(jMainPicture);
        jMainPicture.setBounds(0, 0, 630, 410);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
        int dialogButton = JOptionPane.showConfirmDialog(null, "Сигурни ли сте, че искате излезнете!", "Вход", JOptionPane.YES_NO_OPTION);
        if (dialogButton == JOptionPane.YES_OPTION) {
            System.exit(0);
            if (dialogButton == JOptionPane.NO_OPTION) {
                remove(dialogButton);
            }
        }
    }//GEN-LAST:event_jbtnCancelActionPerformed

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        Connection connection;
        PreparedStatement ps;
        try {
            connection = getConnection();
            ps = connection.prepareStatement("select\n"
                    + "  U.ID, U.USERNAME, U.PASSWORD, U.USER_TYPE\n"
                    + "FROM\n"
                    + "  USERS U\n"
                    + "WHERE\n"
                    + "  U.USERNAME = ? and U.PASSWORD = hash(cast(? as DM_STRING20))");
            ps.setString(1, jtxtUserName.getText());
            ps.setString(2, String.valueOf(jTxtPassword.getPassword()));
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                userType = rs.getInt("USER_TYPE");
                user = rs.getString("USERNAME");
                userID = rs.getInt("ID");
                setVisible(false);
                MainForm main = new MainForm();
                main.setVisible(true);
                checkStatus();
                if (userType == 2) {
                    main.jmReports.setVisible(false);
                    main.jbtnFastFirm.setVisible(false);
                    main.jtbnFastPriceLists.setVisible(false);
                    main.jmiFirms.setVisible(false);
                    main.jmiPriceList.setVisible(false);
                    main.jmiMeasure.setVisible(false);
                    main.jmiChannels.setVisible(false);
                    main.jmiDealType.setVisible(false);
                    main.JmiPayments.setVisible(false);
                    main.jmiCountries.setVisible(false);
                    main.jmiGenerator.setVisible(false);
                    main.jbtnArchiveDb.setVisible(false);;
                    main.jbtnImport.setVisible(false);
                    main.jmiFTPArchive.setVisible(false);
                    main.jmiRest.setVisible(false);
                    main.jmiImport.setVisible(false);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Грешен Потребител/Парола!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnLoginActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jMainPicture;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jTxtPassword;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JLabel jlbLoginForm;
    private javax.swing.JLabel jlbPass;
    private javax.swing.JLabel jlbUsername;
    private javax.swing.JTextField jtxtUserName;
    // End of variables declaration//GEN-END:variables
}
