/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Compnay;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import static Tools.getConnection.getConnection;

/**
 *
 * @author Viko
 */
public class myCompany extends javax.swing.JFrame {

    /**
     * Creates new form myCompany
     */
    public myCompany() {
        initComponents();
    }
    String ImgPath = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public ImageIcon ResizeImage(String ImagePath, byte[] pic) {
        ImageIcon myImage = null;
        if (ImagePath != null) {
            myImage = new ImageIcon(ImagePath);
        } else {
            myImage = new ImageIcon(pic);
        }

        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(jChoosedPicture.getWidth(), jChoosedPicture.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
    }

    private boolean checkInputs() {
        if (jtxtName.getText().isEmpty()
                || jtxtState.getText().isEmpty()
                || jtxtCity.getText().isEmpty()
                || jtxtAddress.getText().isEmpty()
                || jtxtMol.getText().isEmpty()
                || jtxtVatPercent.getText().isEmpty()
                || jtxtPhone.getText().isEmpty()
                || jtxtSite.getText().isEmpty()
                || jtxtEmail.getText().isEmpty()
                || jtxtBank.getText().isEmpty()
                || jtxtConto.getText().isEmpty()
                || jtxtIBAN.getText().isEmpty()
                || jtxtBIC.getText().isEmpty()
                || jtxtVatNumber.getText().isEmpty()
                || jtxtGreicht.getText().isEmpty()
                || jtxtHRB.getText().isEmpty()) {
            return true;
        }
        return false;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jChoosedPicture = new javax.swing.JLabel();
        jbtnChoosePicture = new javax.swing.JButton();
        jtxtName = new javax.swing.JTextField();
        jtxtState = new javax.swing.JTextField();
        jtxtCity = new javax.swing.JTextField();
        jtxtBank = new javax.swing.JTextField();
        jtxtVatPercent = new javax.swing.JTextField();
        jtxtBIC = new javax.swing.JTextField();
        jtxtPhone = new javax.swing.JTextField();
        jtxtAddress = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jtxtIBAN = new javax.swing.JTextField();
        jtxtMol = new javax.swing.JTextField();
        jtxtConto = new javax.swing.JTextField();
        jtxtVatNumber = new javax.swing.JTextField();
        jtxtSite = new javax.swing.JTextField();
        jtxtGreicht = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jtxtHRB = new javax.swing.JTextField();
        jtbnSave = new javax.swing.JButton();
        jbtnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Моята фирма");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jChoosedPicture.setBackground(new java.awt.Color(153, 153, 153));
        jChoosedPicture.setOpaque(true);

        jbtnChoosePicture.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnChoosePicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Compnay/picture.png"))); // NOI18N
        jbtnChoosePicture.setText("Изберете снимка");
        jbtnChoosePicture.setToolTipText("Това е лого на фирмата за фактурите!");
        jbtnChoosePicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChoosePictureActionPerformed(evt);
            }
        });

        jtxtVatPercent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtVatPercentFocusLost(evt);
            }
        });

        jLabel1.setText("Мейл:");

        jLabel2.setText("Банка:");

        jLabel3.setText("Име:");

        jLabel4.setText("Държава:");

        jLabel5.setText("ДДС процент:");

        jLabel6.setText("Град:");

        jLabel7.setText("Адрес:");

        jLabel8.setText("IBAN:");

        jLabel9.setText("Конто номер:");

        jLabel10.setText("BIC:");

        jLabel11.setText("ДДС номер:");

        jLabel12.setText("МОЛ:");

        jLabel14.setText("Gericht:");

        jLabel16.setText("Телефон:");

        jLabel17.setText("Сайт:");

        jLabel18.setText("HRB:");

        jtbnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sale/Save32.png"))); // NOI18N
        jtbnSave.setText("Запис");
        jtbnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnSaveActionPerformed(evt);
            }
        });

        jbtnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sale/Delete32.png"))); // NOI18N
        jbtnClose.setText("Изход");
        jbtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnChoosePicture)
                    .addComponent(jChoosedPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel7)
                        .addComponent(jLabel12)
                        .addComponent(jLabel16)
                        .addComponent(jLabel5)
                        .addComponent(jtxtVatPercent)
                        .addComponent(jtxtMol)
                        .addComponent(jtxtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                        .addComponent(jtxtState)
                        .addComponent(jtxtCity)
                        .addComponent(jtxtAddress)
                        .addComponent(jtxtName))
                    .addComponent(jLabel17)
                    .addComponent(jtxtSite, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(jtxtIBAN)
                    .addComponent(jLabel10)
                    .addComponent(jtxtBIC)
                    .addComponent(jLabel11)
                    .addComponent(jtxtGreicht)
                    .addComponent(jtxtEmail)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jtxtConto)
                    .addComponent(jLabel9)
                    .addComponent(jtxtVatNumber)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18)
                    .addComponent(jtxtHRB, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(jtxtBank))
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtbnSave)
                .addGap(29, 29, 29)
                .addComponent(jbtnClose)
                .addGap(212, 212, 212))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jChoosedPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnChoosePicture)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtMol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtVatPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtConto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtIBAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtBIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel11)
                        .addGap(4, 4, 4)
                        .addComponent(jtxtVatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtGreicht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtHRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtbnSave)
                    .addComponent(jbtnClose))
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnChoosePictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChoosePictureActionPerformed
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));

        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images", "jpg", "png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            jChoosedPicture.setIcon(ResizeImage(path, null));
            ImgPath = path;
        } else {
            System.out.println("Моля изберете файл");
        }

    }//GEN-LAST:event_jbtnChoosePictureActionPerformed

    private void jtbnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnSaveActionPerformed
        if (checkInputs()) {
            JOptionPane.showMessageDialog(this, "Моля попълнете всички полета!");
        }
        else {
            if (ImgPath == null) {
                try {
                    Connection con = getConnection();
                    PreparedStatement ps = con.prepareStatement("update or insert into MY_COMPANY (ID, NAME, COUNTRY, CITY, ADDRESS, MOL, VAT_PERCENTAGE, PHONES, SITE, MAIL, BANK,\n"
                            + "CONTO_NU, IBAN, BIC, VAT_NUMBER, GREICHT, HRB)\n"
                            + "values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,\n"
                            + "?, ?, ?, ?, ?)\n"
                            + "matching (ID)");
                    ps.setInt(1, 1);
                    ps.setString(2, jtxtName.getText());
                    ps.setString(3, jtxtState.getText());
                    ps.setString(4, jtxtCity.getText());
                    ps.setString(5, jtxtAddress.getText());
                    ps.setString(6, jtxtMol.getText());
                    ps.setString(7, jtxtVatPercent.getText());
                    ps.setString(8, jtxtPhone.getText());
                    ps.setString(9, jtxtSite.getText());
                    ps.setString(10, jtxtEmail.getText());
                    ps.setString(11, jtxtBank.getText());
                    ps.setString(12, jtxtConto.getText());
                    ps.setString(13, jtxtIBAN.getText());
                    ps.setString(14, jtxtBIC.getText());
                    ps.setString(15, jtxtVatNumber.getText());
                    ps.setString(16, jtxtGreicht.getText());
                    ps.setString(17, jtxtHRB.getText());

                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Записано в базата данни!");
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
            } else {
                try {
                    Connection con = getConnection();
                    PreparedStatement ps = con.prepareStatement("update or insert into MY_COMPANY (ID, NAME, COUNTRY, CITY, ADDRESS, MOL, LOGO, VAT_PERCENTAGE, PHONES, SITE, MAIL, BANK,\n"
                            + "CONTO_NU, IBAN, BIC, VAT_NUMBER, GREICHT, HRB)\n"
                            + "values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,\n"
                            + "?, ?, ?, ?, ?, ?)\n"
                            + "matching (ID)");
                    ps.setInt(1, 1);
                    ps.setString(2, jtxtName.getText());
                    ps.setString(3, jtxtState.getText());
                    ps.setString(4, jtxtCity.getText());
                    ps.setString(5, jtxtAddress.getText());
                    ps.setString(6, jtxtMol.getText());
                    InputStream img = new FileInputStream(new File(ImgPath));
                    ps.setBlob(7, img);
                    ps.setString(8, jtxtVatPercent.getText());
                    ps.setString(9, jtxtPhone.getText());
                    ps.setString(10, jtxtSite.getText());
                    ps.setString(11, jtxtEmail.getText());
                    ps.setString(12, jtxtBank.getText());
                    ps.setString(13, jtxtConto.getText());
                    ps.setString(14, jtxtIBAN.getText());
                    ps.setString(15, jtxtBIC.getText());
                    ps.setString(16, jtxtVatNumber.getText());
                    ps.setString(17, jtxtGreicht.getText());
                    ps.setString(18, jtxtHRB.getText());

                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Записано в базата данни!");
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(myCompany.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jtbnSaveActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void jtxtVatPercentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtVatPercentFocusLost
        if (!jtxtVatPercent.getText().isEmpty()) {
            try {
                DecimalFormat dc = new DecimalFormat("0.00");
                String formattedText = dc.format(Double.parseDouble(jtxtVatPercent.getText()));
                jtxtVatPercent.setText(formattedText.replace(",", "."));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Грешен формат!");
                jtxtVatPercent.setText("");
            }
        }
    }//GEN-LAST:event_jtxtVatPercentFocusLost

    private void jbtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jbtnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new myCompany().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel jChoosedPicture;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbtnChoosePicture;
    private javax.swing.JButton jbtnClose;
    private javax.swing.JButton jtbnSave;
    public static javax.swing.JTextField jtxtAddress;
    public static javax.swing.JTextField jtxtBIC;
    public static javax.swing.JTextField jtxtBank;
    public static javax.swing.JTextField jtxtCity;
    public static javax.swing.JTextField jtxtConto;
    public static javax.swing.JTextField jtxtEmail;
    public static javax.swing.JTextField jtxtGreicht;
    public static javax.swing.JTextField jtxtHRB;
    public static javax.swing.JTextField jtxtIBAN;
    public static javax.swing.JTextField jtxtMol;
    public static javax.swing.JTextField jtxtName;
    public static javax.swing.JTextField jtxtPhone;
    public static javax.swing.JTextField jtxtSite;
    public static javax.swing.JTextField jtxtState;
    public static javax.swing.JTextField jtxtVatNumber;
    public static javax.swing.JTextField jtxtVatPercent;
    // End of variables declaration//GEN-END:variables

    private static class RunnableImpl implements Runnable {

        public RunnableImpl() {
        }

        public void run() {
            new myCompany().setVisible(true);
        }
    }
}
