/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package settings;

import consultation.ConsultationDelivery;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static Tools.getConnection.getConnection;

/**
 *
 * @author Viko
 */
public class Measures extends javax.swing.JFrame {

    /**
     * Creates new form Measures
     */
    public Measures() {
        initComponents();
        Show_Measures();
        jTable1.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 12));
    }

     private void Show_Measures(){
      try{
      String ID = null;
      String nameBG = null;
      String shortNameBG = null;
      String nameEN = null;
      String shortNameEN = null;
      String nameDE = null;
      String shortNameDE = null;
      DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
      model.setRowCount(0);
      Connection con = getConnection();
      PreparedStatement ps = con.prepareStatement("select\n" +
                                                "  M.ID, M.NAME_DE, M.SHORT_NAME_DE, M.NAME_EN, M.SHORT_NAME_EN, M.NAME_BG, M.SHORT_NAME_BG\n" +
                                                "from\n" +
                                                "  N_MEASURES M");
       ResultSet rs=ps.executeQuery();
       while(rs.next()){
         ID = rs.getString("ID");
         nameBG = rs.getString("NAME_BG");
         shortNameBG = rs.getString("SHORT_NAME_BG");
         nameEN = rs.getString("NAME_EN");
         shortNameEN = rs.getString("SHORT_NAME_EN");
         nameDE = rs.getString("NAME_DE");
         shortNameDE = rs.getString("SHORT_NAME_DE");
         model.addRow(new Object[]{ID, nameBG, shortNameBG, nameEN, shortNameEN, nameDE, shortNameDE});
       }
      }catch(SQLException e){
        Logger.getLogger(ConsultationDelivery.class.getName()).log(Level.SEVERE, null, e);
      }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbnExit = new javax.swing.JButton();
        jtbnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jtbnAdd = new javax.swing.JButton();
        jtxtID = new javax.swing.JTextField();
        jtxtShortNameBG = new javax.swing.JTextField();
        jxtFullNameBG = new javax.swing.JTextField();
        jtxtShortNameEN = new javax.swing.JTextField();
        jtxtFullNameEN = new javax.swing.JTextField();
        jtxtShortNameDE = new javax.swing.JTextField();
        jtxtFullNameDE = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Мерни единици");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                onExit(evt);
            }
        });

        jtbnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sale/Delete32.png"))); // NOI18N
        jtbnExit.setText("Изход");
        jtbnExit.setFocusPainted(false);
        jtbnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnExitActionPerformed(evt);
            }
        });

        jtbnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/article/Update32.png"))); // NOI18N
        jtbnUpdate.setText("Обнови");
        jtbnUpdate.setFocusPainted(false);
        jtbnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnUpdateActionPerformed(evt);
            }
        });

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Номер", "Пълно име(БГ)", "Кратко име(БГ)", "Пълно име(EN)", "Кратко име(EN)", "Пълно име(DE)", "Кратко име(DE)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(180);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(180);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(180);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(50);
        }

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/article/clear24.png"))); // NOI18N
        jButton1.setText("Изчисти");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtbnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/article/Add32.png"))); // NOI18N
        jtbnAdd.setText("Добави");
        jtbnAdd.setFocusPainted(false);
        jtbnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnAddActionPerformed(evt);
            }
        });

        jtxtID.setEditable(false);

        jLabel1.setText("Номер:");

        jLabel2.setText("Пълно име(БГ):");

        jLabel3.setText("К.име(БГ):");

        jLabel4.setText("Пълно име(EN):");

        jLabel5.setText("К.име(EN):");

        jLabel6.setText("Пълно име(DE):");

        jLabel7.setText("К.име(DE):");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Мерни единици");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(423, 423, 423)
                        .addComponent(jtbnUpdate)
                        .addGap(52, 52, 52)
                        .addComponent(jtbnExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtID, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jxtFullNameBG, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtShortNameBG, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtFullNameEN, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtShortNameEN, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtFullNameDE, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtShortNameDE, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(27, 27, 27)
                        .addComponent(jtbnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1065, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jxtFullNameBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtShortNameBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtFullNameEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtShortNameEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtFullNameDE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtShortNameDE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtbnAdd)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtbnUpdate)
                    .addComponent(jtbnExit))
                .addGap(42, 42, 42))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void onExit(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onExit
        setVisible(false);
    }//GEN-LAST:event_onExit

    private void jtbnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnExitActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jtbnExitActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       jtxtID.setText(jTable1.getValueAt(jTable1.getSelectedRow(),0).toString());
       jxtFullNameBG.setText(jTable1.getValueAt(jTable1.getSelectedRow(),1).toString());
       jtxtShortNameBG.setText(jTable1.getValueAt(jTable1.getSelectedRow(),2).toString());
       jtxtFullNameEN.setText(jTable1.getValueAt(jTable1.getSelectedRow(),3).toString());
       jtxtShortNameEN.setText(jTable1.getValueAt(jTable1.getSelectedRow(),4).toString());
       jtxtFullNameDE.setText(jTable1.getValueAt(jTable1.getSelectedRow(),5).toString());
       jtxtShortNameDE.setText(jTable1.getValueAt(jTable1.getSelectedRow(),6).toString());
       jtbnAdd.setEnabled(false);                                 
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       jtxtID.setText("");
       jxtFullNameBG.setText("");
       jtxtShortNameBG.setText("");
       jtxtFullNameEN.setText("");
       jtxtShortNameEN.setText("");
       jtxtFullNameDE.setText("");
       jtxtShortNameDE.setText("");
       jtbnAdd.setEnabled(true); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtbnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnAddActionPerformed
     if(jxtFullNameBG.getText().isEmpty() || jtxtFullNameEN.getText().isEmpty() || jtxtFullNameDE.getText().isEmpty() ||
         jtxtShortNameBG.getText().isEmpty() || jtxtShortNameEN.getText().isEmpty() || jtxtShortNameDE.getText().isEmpty()){
             JOptionPane.showMessageDialog(this, "Моля попълнете всички полета!");
        }else{
          try{                 
          Connection con = getConnection();
          PreparedStatement ps = con.prepareStatement("insert into N_MEASURES (NAME_DE, SHORT_NAME_DE, NAME_EN, SHORT_NAME_EN, NAME_BG, SHORT_NAME_BG)\n" +
                                                        "values (?, ?, ?, ?, ?, ?)");
           ps.setString(1, jtxtFullNameDE.getText());
           ps.setString(2, jtxtShortNameDE.getText());
           ps.setString(3, jtxtFullNameEN.getText());
           ps.setString(4, jtxtShortNameEN.getText());
           ps.setString(5, jxtFullNameBG.getText());
           ps.setString(6, jtxtShortNameBG.getText());
           
           ps.executeUpdate();
           JOptionPane.showMessageDialog(null,"Записано в базата данни!");
           jtxtID.setText("");
           jxtFullNameBG.setText("");
           jtxtFullNameEN.setText("");
           jtxtFullNameDE.setText("");
           jtxtShortNameDE.setText("");
           jtxtShortNameBG.setText("");
           jtxtShortNameEN.setText("");

           Show_Measures();
           
          }catch(HeadlessException | SQLException ex){
             JOptionPane.showMessageDialog(null,ex.getMessage());
            }
         }
    }//GEN-LAST:event_jtbnAddActionPerformed

    private void jtbnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnUpdateActionPerformed
        if(jTable1.getSelectedRow() == -1 || jtxtID.getText().isEmpty()){
             JOptionPane.showMessageDialog(this, "Моля изберете мерната единица, която искате да редактирате!");
        }else{
          try{                 
          Connection con = getConnection();
          PreparedStatement ps = con.prepareStatement("update N_MEASURES\n" +
                                                        "set NAME_DE = ?,\n" +
                                                        "    SHORT_NAME_DE = ?,\n" +
                                                        "    NAME_EN = ?,\n" +
                                                        "    SHORT_NAME_EN = ?,\n" +
                                                        "    NAME_BG = ?,\n" +
                                                        "    SHORT_NAME_BG = ?\n" +
                                                        "where (ID = ?)");
           ps.setString(1, jtxtFullNameDE.getText());
           ps.setString(2, jtxtShortNameDE.getText());
           ps.setString(3, jtxtFullNameEN.getText());
           ps.setString(4, jtxtShortNameEN.getText());
           ps.setString(5, jxtFullNameBG.getText());
           ps.setString(6, jtxtShortNameBG.getText());
           ps.setString(7, jtxtID.getText());
           ps.executeUpdate();
           JOptionPane.showMessageDialog(null,"Успешно направихте промени!");
           
           jtxtID.setText("");
           jxtFullNameBG.setText("");
           jtxtFullNameEN.setText("");
           jtxtFullNameDE.setText("");
           jtxtShortNameDE.setText("");
           jtxtShortNameBG.setText("");
           jtxtShortNameEN.setText("");

           Show_Measures();
           jtbnAdd.setEnabled(true);
          }catch(HeadlessException | SQLException ex){
             JOptionPane.showMessageDialog(null,ex.getMessage());
            }
        }
    }//GEN-LAST:event_jtbnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Measures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Measures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Measures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Measures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Measures().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jtbnAdd;
    private javax.swing.JButton jtbnExit;
    private javax.swing.JButton jtbnUpdate;
    private javax.swing.JTextField jtxtFullNameDE;
    private javax.swing.JTextField jtxtFullNameEN;
    private javax.swing.JTextField jtxtID;
    private javax.swing.JTextField jtxtShortNameBG;
    private javax.swing.JTextField jtxtShortNameDE;
    private javax.swing.JTextField jtxtShortNameEN;
    private javax.swing.JTextField jxtFullNameBG;
    // End of variables declaration//GEN-END:variables
}
