/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package consultation;

import client.Client;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import static Tools.getConnection.getConnection;
import Tools.DropDown;
import static Tools.GetSQL.getSQL;

/**
 *
 * @author Viko
 */
public class Clients extends javax.swing.JFrame {

    /**
     * Creates new form ForDelivery
     */
    public Clients() {
        initComponents();
        Show_Clients();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        jTable1.getTableHeader().setFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 12));
    }

    private void Show_Clients() {
        try {
            int ID = 0;
            String type = null;
            String name = null;
            String country = null;
            String city = null;
            String address = null;
            String vatNumber = null;
            String mol = null;
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            Connection con = getConnection();
            String sql = getSQL(5);
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                ID = rs.getInt("ID");
                type = rs.getString("IS_PERSON");
                name = rs.getString("CLIENT_NAME");
                country = rs.getString("COUNTRY");
                city = rs.getString("CITY");
                address = rs.getString("ADDRESS");
                vatNumber = rs.getString("VAT_NUMBER");
                mol = rs.getString("MOL");
                model.addRow(new Object[]{ID, type, name, country, city, address, vatNumber, mol});
            }
        } catch (SQLException e) {
            Logger.getLogger(ConsultationDelivery.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbCountry = new javax.swing.JComboBox<>();
        jbtnRefresh = new javax.swing.JButton();
        jlbAva = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtnClose = new javax.swing.JButton();

        jbtnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/consultation/refresh.png"))); // NOI18N
        jbtnRefresh.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRefreshActionPerformed(evt);
            }
        });

        setTitle("Клиенти");
        setResizable(false);

        jlbAva.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbAva.setText("Клиенти");

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Тип", "Име", "Държава", "Град", "Адрес", "ДДС номер", "МОЛ/email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(150);
        }

        jbtnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sale/Delete32.png"))); // NOI18N
        jbtnClose.setText("Изход");
        jbtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1047, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
            .addGroup(layout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(jlbAva)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jlbAva)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jbtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jbtnCloseActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2) {
            try {
                Connection con = getConnection();
                int row = jTable1.getSelectedRow();
                int correctModel = jTable1.convertRowIndexToModel(row);
                PreparedStatement ps = con.prepareStatement("select first 1\n"
                        + "C.ID, C.PERSON, C.NAME, C.COUNTRY_ID, CC.NAME COUNTRY, C.CITY, C.ADDRESS, C.VAT_NUMBER, C.MOL\n"
                        + "from\n"
                        + "  CLIENTS C\n"
                        + "  join N_COUNTRIES CC on CC.ID = C.COUNTRY_ID\n"
                        + "where\n"
                        + "  C.ID = " + jTable1.getModel().getValueAt(correctModel, 0));
                ResultSet rs = ps.executeQuery();
                Vector<DropDown> countries = new Vector<>();
                while (rs.next()) {
                    int person = rs.getInt("PERSON");
                    countries.addElement(new DropDown(rs.getInt("COUNTRY_ID"), rs.getString("COUNTRY")));
                    jcbCountry.setModel(new DefaultComboBoxModel(countries));

                    Client client = new Client();
                    Client.fromReport = 1;
                    client.clientID = rs.getInt("ID");
                    client.jcbClientType.setSelectedIndex(0);
                    if (person == 1) {
                        client.jchbPerson.setSelected(true);
                        client.jchbFirm.setSelected(false);
                    } else if (person == 0) {
                        client.jchbFirm.setSelected(true);
                        client.jchbPerson.setSelected(false);
                    }
                    client.jcbCountries.getModel().setSelectedItem(jcbCountry.getModel().getSelectedItem());
                    client.jtxtClientName.setText(rs.getString("NAME"));
                    client.jtxtCity.setText(rs.getString("CITY"));
                    client.jtxtAddress.setText(rs.getString("ADDRESS"));
                    client.jtxtVatNumber.setText(rs.getString("VAT_NUMBER"));
                    client.jtxtMOL.setText(rs.getString("MOL"));

                    countries.clear();
                    client.isFromForm = 0;
                    client.setVisible(true);
                }
            } catch (SQLException ex) {
                Logger.getLogger(ConsultationSales.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jbtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRefreshActionPerformed
        Show_Clients();
    }//GEN-LAST:event_jbtnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForDelivery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnClose;
    public static javax.swing.JButton jbtnRefresh;
    public javax.swing.JComboBox<String> jcbCountry;
    private javax.swing.JLabel jlbAva;
    // End of variables declaration//GEN-END:variables
}
