/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import delivery.Delivery;
import java.io.IOException; // dont remove for INI file
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static Tools.getConnection.getConnection;
import Tools.DropDown;
import static Tools.setValuesComboBox.setValuesComboBox;
import sale.SALE;
import consultation.Clients;

/**
 *
 * @author Viko
 */
public class Client extends javax.swing.JFrame {

    public int isFromForm = 0;
    public int clientID = 0;
    public static int fromReport = 0;

    /**
     * Creates new form Client
     */
    public Client() {
        initComponents();
        // set values comboBox ClientType
        setValuesComboBox("select TC.ID, TC.TYPE_NAME from N_TYPES_CLIENTS TC", jcbClientType, false, -1, false);
        // set values comboBox Countries
        setValuesComboBox("select C.ID, C.NAME from N_COUNTRIES C order by C.SORTING asc", jcbCountries, true, -1, false);
        jchbPerson.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbClient = new javax.swing.JLabel();
        jchbPerson = new javax.swing.JCheckBox();
        jchbFirm = new javax.swing.JCheckBox();
        jtxtClientName = new javax.swing.JTextField();
        jlbClientName = new javax.swing.JLabel();
        jcbCountries = new javax.swing.JComboBox<>();
        jlbCountries = new javax.swing.JLabel();
        jcbClientType = new javax.swing.JComboBox<>();
        jlbType = new javax.swing.JLabel();
        jtxtCity = new javax.swing.JTextField();
        jlbCity = new javax.swing.JLabel();
        jtxtAddress = new javax.swing.JTextField();
        jlbAddress = new javax.swing.JLabel();
        jtxtMOL = new javax.swing.JTextField();
        jlbMOL = new javax.swing.JLabel();
        jtxtVatNumber = new javax.swing.JTextField();
        jlbVatNumber = new javax.swing.JLabel();
        jtbnSave = new javax.swing.JButton();
        jbtnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Клиенти");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                onExit(evt);
            }
        });

        jlbClient.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbClient.setText("     Клиент/Доставчик");
        jlbClient.setToolTipText("");

        jchbPerson.setText("Частно лице");
        jchbPerson.setFocusPainted(false);
        jchbPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchbPersonActionPerformed(evt);
            }
        });

        jchbFirm.setText("Фирма");
        jchbFirm.setFocusPainted(false);
        jchbFirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchbFirmActionPerformed(evt);
            }
        });

        jlbClientName.setText("Име:");

        jlbCountries.setText("Държава:");

        jlbType.setText("Тип:");

        jlbCity.setText("Град:");

        jlbAddress.setText("Адрес:");

        jlbMOL.setText("МОЛ/email:");

        jlbVatNumber.setText("ДДС номер:");

        jtbnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sale/Save32.png"))); // NOI18N
        jtbnSave.setText("Запис");
        jtbnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnSaveActionPerformed(evt);
            }
        });

        jbtnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sale/Delete32.png"))); // NOI18N
        jbtnClose.setText("Изход");
        jbtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbClient)
                            .addComponent(jlbVatNumber)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtxtClientName, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                                .addComponent(jtxtAddress)
                                .addComponent(jtxtMOL)
                                .addComponent(jtxtVatNumber)
                                .addComponent(jlbMOL)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jchbPerson)
                                    .addGap(18, 18, 18)
                                    .addComponent(jchbFirm))
                                .addComponent(jlbClientName)
                                .addComponent(jcbClientType, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlbType)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlbCountries)
                                        .addComponent(jlbAddress)
                                        .addComponent(jcbCountries, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlbCity)
                                        .addComponent(jtxtCity))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jtbnSave)
                        .addGap(29, 29, 29)
                        .addComponent(jbtnClose)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jlbClient)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchbPerson)
                    .addComponent(jchbFirm))
                .addGap(5, 5, 5)
                .addComponent(jlbType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbClientType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jlbClientName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtClientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCountries)
                    .addComponent(jlbCity))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbCountries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbAddress)
                .addGap(10, 10, 10)
                .addComponent(jtxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jlbMOL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtMOL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbVatNumber)
                .addGap(5, 5, 5)
                .addComponent(jtxtVatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtbnSave)
                    .addComponent(jbtnClose))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jbtnCloseActionPerformed
    private void jtbnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnSaveActionPerformed
        if (jcbClientType.getSelectedIndex() == -1 || jtxtClientName.getText().isEmpty() || jcbCountries.getSelectedIndex() == -1
                || jtxtCity.getText().isEmpty() || jtxtAddress.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Моля попълнете всички полета!");
        } else {
            int personValue = 0;
            if (jchbPerson.isSelected()) {
                personValue = 1;
            } else {
                personValue = 0;
            }
            try {
                Connection con = getConnection();
                if (clientID == 0) {
                    PreparedStatement ps = con.prepareStatement("insert into CLIENTS (TYPE_ID, PERSON, NAME, COUNTRY_ID, CITY, ADDRESS, VAT_NUMBER, MOL)\n"
                            + "values (?,?,?,?,?,?,?,?)");

                    ps.setInt(1, (((DropDown) jcbClientType.getSelectedItem()).getId()));
                    ps.setInt(2, personValue);
                    ps.setString(3, jtxtClientName.getText());
                    ps.setInt(4, (((DropDown) jcbCountries.getSelectedItem()).getId()));
                    ps.setString(5, jtxtCity.getText());
                    ps.setString(6, jtxtAddress.getText());
                    ps.setString(8, jtxtMOL.getText());
                    ps.setString(7, jtxtVatNumber.getText());

                    ps.executeUpdate();

                    if (isFromForm == 1) {
                        if (Client.jcbClientType.getSelectedIndex() == 0) {
                            this.setVisible(false);
                            SALE.savedClient = 1;
                            SALE.jbtnRefreshSale.doClick();
                        } else if (Client.jcbClientType.getSelectedIndex() == 1) {
                            this.setVisible(false);
                            Delivery.savedSupplier = 1;
                            Delivery.jbtnRefreshDelivery.doClick();
                        }
                    }
                    jchbPerson.setSelected(false);
                    jchbFirm.setSelected(false);
                    jcbClientType.setSelectedIndex(-1);
                    jtxtClientName.setText("");
                    jcbCountries.setSelectedIndex(-1);
                    jtxtCity.setText("");
                    jtxtAddress.setText("");
                    jtxtMOL.setText("");
                    jtxtVatNumber.setText("");
                } else {
                    PreparedStatement ps = con.prepareStatement("update CLIENTS\n"
                            + "set TYPE_ID = ?,\n"
                            + "    PERSON = ?,\n"
                            + "    NAME = ?,\n"
                            + "    COUNTRY_ID = ?,\n"
                            + "    CITY = ?,\n"
                            + "    ADDRESS = ?,\n"
                            + "    VAT_NUMBER = ?,\n"
                            + "    MOL = ?\n"
                            + "where (ID = ?)");

                    ps.setInt(1, (((DropDown) jcbClientType.getSelectedItem()).getId()));
                    ps.setInt(2, personValue);
                    ps.setString(3, jtxtClientName.getText());
                    ps.setInt(4, (((DropDown) jcbCountries.getSelectedItem()).getId()));
                    ps.setString(5, jtxtCity.getText());
                    ps.setString(6, jtxtAddress.getText());
                    ps.setString(8, jtxtMOL.getText());
                    ps.setString(7, jtxtVatNumber.getText());
                    ps.setInt(9, clientID);
                    ps.executeUpdate();
                    if (fromReport == 1) {
                        Clients.jbtnRefresh.doClick();
                    }
                }
            } catch (HeadlessException | SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_jtbnSaveActionPerformed

    private void onExit(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onExit
        jbtnClose.doClick();
    }//GEN-LAST:event_onExit

    private void jchbPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchbPersonActionPerformed
        if (jchbPerson.isSelected()) {
            jchbFirm.setSelected(false);
        } else {
            jchbFirm.setSelected(true);
        }
    }//GEN-LAST:event_jchbPersonActionPerformed

    private void jchbFirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchbFirmActionPerformed
        if (jchbFirm.isSelected()) {
            jchbPerson.setSelected(false);
        } else {
            jchbPerson.setSelected(true);
        }
    }//GEN-LAST:event_jchbFirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Client().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnClose;
    public static javax.swing.JComboBox<String> jcbClientType;
    public javax.swing.JComboBox<String> jcbCountries;
    public javax.swing.JCheckBox jchbFirm;
    public javax.swing.JCheckBox jchbPerson;
    private javax.swing.JLabel jlbAddress;
    private javax.swing.JLabel jlbCity;
    private javax.swing.JLabel jlbClient;
    private javax.swing.JLabel jlbClientName;
    private javax.swing.JLabel jlbCountries;
    private javax.swing.JLabel jlbMOL;
    private javax.swing.JLabel jlbType;
    private javax.swing.JLabel jlbVatNumber;
    private javax.swing.JButton jtbnSave;
    public javax.swing.JTextField jtxtAddress;
    public javax.swing.JTextField jtxtCity;
    public javax.swing.JTextField jtxtClientName;
    public javax.swing.JTextField jtxtMOL;
    public javax.swing.JTextField jtxtVatNumber;
    // End of variables declaration//GEN-END:variables
}
