/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rest;

import com.sun.net.httpserver.HttpServer;
import java.io.IOException;
import java.net.InetSocketAddress;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.soap.SOAPConnection;
import javax.xml.soap.SOAPConnectionFactory;
import javax.xml.soap.SOAPMessage;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import static rest.ApacheHttpClientGet.getFromWeb;
import static soap.vies_soap.*;
/**
 *
 *
 * @author Viko
 */
public class RestService extends javax.swing.JFrame {

    /**
     * Creates new form RestExample
     */
    public RestService() {
        initComponents();
    }
    
    public void createServer() throws IOException{
     
      HttpServer server = HttpServer.create(new InetSocketAddress(8500), 0);
      server.createContext("/api/v1/articles", new ArticleHandler());
      server.createContext("/api/v1/categories", new CategoryHandler());
      server.createContext("/api/v1/clients", new ClientHandler());
      server.createContext("/api/v1/masterDeals", new MasterDealsHandler());
      server.createContext("/api/v1/detailDeals", new DetailDealsHandler());
      server.start();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jbtnSOAP = new javax.swing.JButton();

        setTitle("РЕСТ");

        jButton1.setText("Стартирай РЕСТ услугата");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("    Рест услугата се използва за\n    комуникация межди платформата  \n    и външни системи.\n    След като бъде стартирана \n    ще получаваме и изпращаме данни на \n    външни системи.");
        jScrollPane1.setViewportView(jTextArea1);

        jbtnSOAP.setText("Тест SOAP");
        jbtnSOAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSOAPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jbtnSOAP)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jbtnSOAP)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            createServer();
            String output = getFromWeb("http://localhost:8080/api/v1/categories");
            JSONArray array = new JSONArray(output);
            for(int i=0; i < array.length(); i++) {
                JSONObject object = array.getJSONObject(i);
                //System.out.println(object.getInt("id"));
                System.out.println(object.getString("name"));
      }
            System.out.println(output);
            JOptionPane.showMessageDialog(null, "РЕСТ услугата е стартирана успешно"); 
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(RestService.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JSONException ex) {
            Logger.getLogger(RestService.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnSOAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSOAPActionPerformed
        try {
            String fullVatNumber = "DE308177468";
            //String countryCode = "DE";
            //String vatNumber = "308177468";
            String countryCode = fullVatNumber.substring(0, 2);
            String vatNumber = fullVatNumber.substring(2, fullVatNumber.length());

            // Create SOAP Connection
            SOAPConnectionFactory soapConnectionFactory = SOAPConnectionFactory.newInstance();
            SOAPConnection soapConnection = soapConnectionFactory.createConnection();

            // Send SOAP Message to SOAP Server
            String url = "http://ec.europa.eu/taxation_customs/vies/services/checkVatService";
            SOAPMessage soapResponse = soapConnection.call(createSOAPRequest(countryCode, vatNumber), url);

            // Process the SOAP Response
            String isValid = printSOAPResponse(soapResponse);
            String validBG = "";
            if("true".equals(isValid)) 
                validBG = "Валиден";
            else
                validBG = "Невалиден";
            JOptionPane.showMessageDialog(null, validBG); 
            soapConnection.close();
        } catch (Exception e) {
            System.err.println("Грешка при изпращането на заявка до сървъра!");
            JOptionPane.showMessageDialog(null, "Грешка при изпращането на заявка до сървъра!"); 
            e.printStackTrace();
        }
    }//GEN-LAST:event_jbtnSOAPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
     
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbtnSOAP;
    // End of variables declaration//GEN-END:variables
}
